# Generated by Django 3.1 on 2020-08-31 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='frectangle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dots', to='polygon_rest.frectangle'),
        ),
    ]
