# Generated by Django 3.1 on 2020-08-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon_rest', '0003_auto_20200831_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectangle',
            name='children',
        ),
        migrations.AddField(
            model_name='rectangle',
            name='children_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='polygon_rest.rectangle'),
        ),
    ]
