# Generated by Django 3.1 on 2020-08-31 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('desc', models.CharField(default='Пустая точка', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polygon_rest.rectangle')),
                ('d0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d0', to='polygon_rest.dot')),
                ('d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d1', to='polygon_rest.dot')),
                ('d2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d2', to='polygon_rest.dot')),
                ('d3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d3', to='polygon_rest.dot')),
            ],
        ),
        migrations.CreateModel(
            name='FRectangle',
            fields=[
                ('rectangle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polygon_rest.rectangle')),
            ],
            bases=('polygon_rest.rectangle',),
        ),
        migrations.AddField(
            model_name='dot',
            name='frectangle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dots', to='polygon_rest.frectangle'),
        ),
    ]
