# Generated by Django 3.1 on 2020-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon_rest', '0004_auto_20200831_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='desc',
            field=models.CharField(default='Точка базы', max_length=255),
        ),
    ]
